default: &default
  adapter: postgresql
#  schema_search_path: teneo, teneo_password, public
  schema_search_path: teneo
  encoding: unicode
  pool: 3

  host: localhost
  port: 5432

  username: teneo
  password: teneo

  dba_name: teneo_dba
  dba_pass: teneo_dba

  migrations_paths:
    - "db/migrate"

development:
  <<: *default
  database: teneo_data_model_dev

test:
  <<: *default
  database: teneo_data_model_test

production:
  <<: *default
  database: teneo_data_model
